[ovh]
type = s3
provider = Other
env_auth = false
access_key_id = 47f8ff915ea34c60bd3a0d8950ccaa56
secret_access_key = c87b828e3a4642f998b32d9ab1b238b5
endpoint = https://s3.gra.io.cloud.ovh.net
region = gra
acl = private